### PR TITLE
Re-enable Staking, Delegation and limited swap functionality on classic-core

### PR DESCRIPTION
**Pull request by ZaradarDFDS**
## Summary of changes

Revert Terra Classic-Core to use the version of the Cosmos SDK proposed by @edk208 to allow delegation and validator node registation to function again so that all LUNC holders may choose to delegate and vote on governance proposals.

In addition this PR also contains a fix to the swap logic in the market keeper which will re-enable limited swapping under the following conditions:

- LUNC => Terra swapping would work as normal to allow the LUNC pool to get drained if/when the stablecoins pick up again.

- Terra => LUNC swapping would only work if the LUNC pool does not exceed 2T tokens. If it fails it will throw a new sdkerror called ErrExceedMaxDelta to indicate that the swap is not permissible as it would exceed the new LUNC "MaxDelta". 

If accepted swapping would be re-enabled a blockHeight 9000000 and MinStabilitySpread would change from 100% to 98% to slowly allow the mint/burn logic to correct the extreme imbalance with regards to the supply of LUNC tokens.

Lastly this PR will also open the IBC channels that where closed. This will also happen at blockHeight 9000000

This PR is only intended as a short-term fix. A more long term solution for the algo will need to be found but with this fix we would allow a certain amount of swapping to take place again and thus reintroduce some utility in LUNC that could help burn the total supply faster and restore some amount of confidence in the chain/token.

## Report of required housekeeping

- [ ] Github issue OR spec proposal link
- [ ] Wrote tests
- [ ] Updated API documentation (client/lcd/swagger-ui/swagger.yaml)
- [ ] Added a relevant changelog entry: clog add [section] [stanza] [message]

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

### CODE REVIEW

**Review by Raider7019 — DISMISSED** [review]
I support this pull request which introduces essential changes that will enable the Terra Classic blockchain to start functioning again according to the intent of the protocol defintion as described in the Terra Classic documentation.

**Comment by iamderafms** [comment]
Great job

**Comment by dfunk009** [comment]
you can't reenable swaps with 6.9T supply lol

**Comment by ZaradarDFDS** [comment]
> you can't reenable swaps with 6.9T supply lol

And why is that? If you can only swap LUNC into a derivative (like UST) then you will create less supply. To please explain what I am missing here? :)

**Comment by dfunk009** [comment]
> > you can't reenable swaps with 6.9T supply lol
> 
> And why is that? If you can only swap LUNC into a derivative (like UST) then you will create less supply. So please explain what I am missing here? :)

if you swap LUNC to UST you will burn LUNC and mint UST. UST already has a supply overhang. Both LUNC and UST need to be burned to reduce the supply

**Comment by ZaradarDFDS** [comment]
You cant really compare a synthetic derivative (UST) with the asset its derived from (LUNC). But regardless of that discussion I see no harm in re-enabling the minting of UST if somehow someone decided to re-peg the market and become a future market maker. So from a pure functionality perspective it makes no sense to have this feature disabled as long as we can avoid minting more new LUNC, which the current proposed hard cap of 2T LUNC will ensure. So I don't really see an issue here?

**Comment by Rexyz123** [comment]
I think before it is reconnected the supply would need to be back down to 340,000,000 as before, or at the very most 1,000,000,000. 
Also I'd rather keep LUNC and UST separated until we've consulted with third parties on this such as VB and cz... there is so much to lose if we screw up again. 
Also before any attempt to repeat there'd need to be independent auditing of our algorithm and connectivity. Even if what you suggest is acceptable, we'd need this scrutiny to give credence to using UST again... and that maybe a nearly impossible mission. Would you put your life savings in it again and trust it? So at this time I would not support a reconnection.

**Comment by terrafried** [comment]
ableist group run by one guy who thinks he is the leader. lots of disabled people in this group. i am one that has been driven out by the toxic environment of their discord. dont accept this group as leaders. lets create a group that welcomes all people.

**Comment by ZaradarDFDS** [comment]
> I think before it is reconnected the supply would need to be back down to 340,000,000 as before, or at the very most 1,000,000,000. Also I'd rather keep LUNC and UST separated until we've consulted with third parties on this such as VB and cz... there is so much to lose if we screw up again. Also before any attempt to repeat there'd need to be independent auditing of our algorithm and connectivity. Even if what you suggest is acceptable, we'd need this scrutiny to give credence to using UST again... and that maybe a nearly impossible mission. Would you put your life savings in it again and trust it? So at this time I would not support a reconnection.

Its for other people to worry about how/when/if to rebuild UST. But if we do not enable the option it will never happen. :)

**Comment by Raider7019** [comment]
> It might be more judicious to separate in 2 PR. 1/ reactivation from staking and delegation 2/ the swap
> 
> which are 2 very distinct things.

Thanks for your comments! We have two other PRs (#775  and #776) which provide (two different options) of reactivation of delegation and validator registration only. The idea behind this PR was to provide the third option of doing all changes together.

**Comment by ZaradarDFDS** [comment]
Closing this PR. Will re-open a new one from terra-rebels when we are done with the burn tax proposal

**Pull request closed without merging**
