### PR TITLE
(Re)Enable Staking and Delegation on classic-core

### PR DESCRIPTION
**Pull request by edk208**
This PR reverts back to the commit to cosmos-sdk to the state right before the CreateValidator and Delegate functions were disabled at height 7603700.  

This will renable staking and delegation on luna classic.

## Summary of changes

replace go.mod deps for terra-money/cosmos-sdk to the version before staking was removed.
the commit right before was pull request #37 on release v0.44.x
https://github.com/terra-money/cosmos-sdk/commits/release/v0.44.x

### CODE REVIEW

**Comment by Raider7019** [comment]
Thanks very much for taking the time to comment on my PR #776. I noticed that your PR #775 is reverting the cosmos-sdk version to a more recent version than was used at the time that the original changes to disable delegation and validator registration were made. 

As per the commit from @alexanderbez (https://github.com/terra-money/classic-core/commit/512954bf10e2e3485879a68cf38572c40d968abf) he is replacing github.com/terra-money/cosmos-sdk v0.44.5-terra.2 with github.com/terra-money/cosmos-sdk v0.44.6-0.20220512154111-515df8b16c89. So in PR #776 I am reverting to github.com/terra-money/cosmos-sdk v0.44.5-terra.2. 

Am I missing something, as to why your PR #775 is reverting to github.com/terra-money/cosmos-sdk v0.44.6-0.20220331002058-d6d8837778da?

**Comment by edk208** [comment]
I originally also thought to go back to v0.44.5-terra.2.  I think it also works to roll back to this point.
The only reason I rolled back to v0.44.6-0.20220331002058-d6d8837778da is because it seems like there might have been one fairly benign commit between v0.44.5-terra.2 and v0.44.6-0.20220512154111-515df8b16c89 that bumped actions/cache from 2.1.6 to 3.0.1 that adds a few things as described by the https://github.com/actions/cache/releases

**Comment by Raider7019** [comment]
Thanks for clarifying!

**Review by Raider7019 — APPROVED** [review]

**Review by ZaradarDFDS — APPROVED** [review]

**Comment by dfunk009** [comment]
why haven't you created a proposal for this?

**Comment by dfunk009** [comment]
> As noted by #776, staking was removed as a security measure without a proposal. There is no need for a proposal to re-enable staking. It is fundamental to a proof-of-stake blockchain and should be enabled as soon as possible.

The cost of attack at this point will be some $10k if re-enabled.

**Comment by dfunk009** [comment]
another thing - market module (on-chain swaps) were disabled after staking was disabled. reverting this will also enable market swaps which will again result in a death spiral

**Comment by Raider7019** [comment]
> reverting this will also enable market swaps which will again result in a death spiral

No, what you wrote above is incorrect.

This PR doesn't touch the code that disabled swaps (and IBC channels), it only reverts the Cosmos SDK dependency a version prior to the one where delegation and validator registration were disabled, such that those messages are accepted by the state machine again.

**Comment by dfunk009** [comment]
maybe @YunSuk-Yeo can chip in?

**Review by mysolo — APPROVED** [review]

**Comment by edk208** [comment]
would break consensus.  see modified PR here https://github.com/terra-money/cosmos-sdk/pull/80

**Pull request closed without merging**
